<?php

declare(strict_types=1);

namespace Flowpack\SiteKickstarter\Domain\Generator\Fusion;

use Flowpack\SiteKickstarter\Domain\Specification\NodeTypeSpecification;
use Flowpack\SiteKickstarter\Domain\Modification\CreateFileModification;
use Flowpack\SiteKickstarter\Domain\Modification\ModificationIterface;
use Neos\Flow\Package\FlowPackageInterface;

class ContentFusionRendererGenerator extends AbstractFusionRendererGenerator
{

    /**
     * @param FlowPackageInterface $package
     * @param NodeTypeSpecification $nodeType
     * @return ModificationIterface
     */
    public function generate(FlowPackageInterface $package, NodeTypeSpecification $nodeType): ModificationIterface
    {
        $packagePath = $this->getRelativePackagePath($package);

        $prototype = <<<EOT
            #
            # Renderer for NodeType {$nodeType->getName()->getFullName()}
            # as configured in {$packagePath}{$nodeType->getNodeTypeConfigurationPath()}
            #
            # @see https://docs.neos.io/cms/manual/rendering
            #
            prototype({$nodeType->getName()->getFullName()}) < prototype(Neos.Neos:ContentComponent) {

                {$this->indent($this->createComponentProps($nodeType))}

                renderer = afx`
                    <div>
                        Autogenerated renderer for NodeType: {$nodeType->getName()->getFullName()}, adjust the following files and remove this comment!
                        <pre>
                         - Data-Model: {$packagePath}{$nodeType->getNodeTypeConfigurationPath()}
                         - Rendering: {$packagePath}{$nodeType->getFusionRenderPath()}
                        </pre>
                        {$this->indent($this->createAfxRenderer($nodeType), 12)}
                    </div>
                `
            }
            EOT;

        return new CreateFileModification(
            $packagePath . $nodeType->getNodeTypeConfigurationPath(),
            $prototype
        );
    }
}
