<?php


namespace Flowpack\SiteKickstarter\Domain\Generator\Fusion;


use Flowpack\SiteKickstarter\Domain\Model\NodeType;
use Flowpack\SiteKickstarter\Domain\Modification\WholeFileModification;
use Flowpack\SiteKickstarter\Domain\Modification\ModificationIterface;

class DocumentFusionGenerator extends AbstractFusionGenerator
{
    /**
     * @param NodeType $nodeType
     * @return ModificationIterface
     */
    public function generate(NodeType $nodeType): ModificationIterface
    {


        $prototype = <<<EOT
            #
            # Renderer for NodeType {$nodeType->getFullName()}
            # as configured in {$nodeType->getYamlFilePath()}
            #
            # @see https://docs.neos.io/cms/manual/rendering
            #
            prototype({$nodeType->getFullName()}) < prototype(Neos.Fusion:Component) {

                {$this->indent($this->createPropertyAccessors($nodeType))}

                renderer = Neos.Neos:Page {
                    head {
                        resources = afx`
                            <link href={StaticResource.uri('{$nodeType->getPackage()->getPackageKey()}', 'Public/Styles/Main.css')} rel="stylesheet" media="all" />
                            <style src={StaticResource.uri('{$nodeType->getPackage()->getPackageKey()}', 'Public/Scripts/Main.js')}></style>
                        `
                    }

                    body = afx`
                        <div>
                            Autogenerated renderer for NodeType: "{$nodeType->getFullName()}", adjust the following files and remove this comment!
                            <pre>
                             - Data-Model: {$nodeType->getYamlFilePath()}
                             - Rendering: {$nodeType->getFusionFilePath()}
                             - Css: {$nodeType->getPackage()->getPackageKey()}/Resources/Public/Styles/Main.css
                             - JS: {$nodeType->getPackage()->getPackageKey()}/Resources/Public/Scripts/Main.css
                            </pre>
                            {$this->indent($this->createAfxRenderer($nodeType), 16)}
                        </div>
                    `
                }
            }
            EOT;

        return new WholeFileModification(
            $nodeType->getFusionFilePath(),
            $prototype
        );
    }
}
