name: build

on:
    push:
        branches:
            - 'master'
    pull_request: ~

jobs:
    test:
        name: "Test (PHP ${{ matrix.php-versions }}, Flow ${{ matrix.flow-versions }})"

        strategy:
            fail-fast: false
            matrix:
                php-versions: [ '7.4' ]
                flow-versions: [ '7.2' ]
#                include:
#                    - php-versions: '7.2'
#                      flow-versions: '6.0'
#                    - php-versions: '8.0'
#                      flow-versions: '7.0'

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2
              with:
                  path: ${{ env.FLOW_FOLDER }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: mbstring, xml, json, zlib, iconv, intl, pdo_sqlite
                  ini-values: date.timezone="Africa/Tunis", opcache.fast_shutdown=0, apc.enable_cli=on

            # - name: Set Flow Version
            #  run: composer require neos/flow ^${{ matrix.flow-versions }} --no-progress --no-interaction

            - name: Run Tests
              run: composer test
